runtime: custom
vm: true

manual_scaling:
    instances: 1

beta_settings:
 # Enable Google Cloud Endpoints API management.
 use_endpoints_api_management: true
 # Specify the OpenAPI (a.k.a. Swagger) specification.
 endpoints_swagger_spec_file: swagger/swagger.yaml
