consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
externalDocs:
  description: GoDoc
  url: https://godoc.org/github.com/goadesign/swagger-service
host: goa-swagger.appspot.com
info:
  contact:
    email: admin@goa.design
    name: The goa team
    url: http://goa.design
  description: The goa Swagger service can render the swagger specification of a goa
    design package given its Go path
  license:
    name: MIT
    url: https://github.com/goadesign/goa/blob/master/LICENSE
  title: goa Swagger specification generation service
  version: ""
paths:
  /_ah/health:
    get:
      description: Perform health check.
      operationId: ae#health
      responses:
        "200":
          description: OK
      schemes:
      - https
      summary: health ae
      tags:
      - ae
  /_ah/start:
    get:
      description: AppEngine start lifecycle event
      operationId: ae#start
      responses:
        "200":
          description: OK
      schemes:
      - https
      summary: start ae
      tags:
      - ae
  /swagger/spec:
    get:
      description: Retrieve Swagger specification for given goa service design package
      operationId: spec#show
      parameters:
      - description: Go package path to goa service design package
        in: query
        name: pkg
        required: true
        type: string
      responses:
        "200":
          description: OK
        "422":
          description: goagen failed to generate the Swagger spec.
      schemes:
      - https
      summary: show spec
      tags:
      - spec
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
  UnprocessableEntity:
    description: goagen failed to generate the Swagger spec.
schemes:
- https
swagger: "2.0"
